"""empty message

Revision ID: cd58ecc3bf09
Revises: 
Create Date: 2022-10-13 23:08:25.812462

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cd58ecc3bf09'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_item',
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('parent_id', postgresql.UUID(), nullable=True),
    sa.Column('type', sa.String(length=6), nullable=False),
    sa.Column('size', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['system_item.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_item_parent_id'), 'system_item', ['parent_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_system_item_parent_id'), table_name='system_item')
    op.drop_table('system_item')
    # ### end Alembic commands ###
